In [1]:
import numpy as np
import pandas as pd

%precision 3

'%.3f'

In [2]:
'%.3f'

'%.3f'

In [3]:
df = pd.read_csv('ch2_scores_em.csv',index_col = 'student number')
df.head()

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [4]:
scores = np.array(df['english'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58])

In [5]:
scores_df = pd.DataFrame({'score':scores},
                         index=pd.Index(['A','B','C','D','E','F','G','H','I','J'],
                                        name='student'))
scores_df

score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
J           58

In [6]:
sum(scores)/len(scores)

55.000

In [7]:
np.mean(scores)

55.000

In [8]:
scores_df.mean()

score    55.0
dtype: float64

In [9]:
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69])

In [10]:
n = len(sorted_scores)
if n & 2 ==0:
    m0 = sorted_scores[n//2-1]
    m1 = sorted_scores[n//2]
    median = (m0+m1) /2
else :
    median = sorted_scores[(n+1)//2-1]
median

np.int64(56)

In [11]:
np.median(scores)

56.500

In [12]:
scores_df.median()

score    56.5
dtype: float64

In [13]:
pd.Series([1,2,3,4,5]).mode()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [14]:
mean=np.mean(scores)
deviation=scores-mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [15]:
another_scores=[50,60,58,54,51,56,57,53,52,59]
another_mean=np.mean(another_scores)
another_deviation=another_scores-another_mean
another_deviation

array([-5.,  5.,  3., -1., -4.,  1.,  2., -2., -3.,  4.])

In [16]:
np.mean(deviation)

0.000

In [17]:
np.mean(another_deviation)

0.000

In [18]:
summary_df=scores_df.copy()
summary_df['deviation']=deviation
summary_df

score  deviation
student                  
A           42      -13.0
B           69       14.0
C           56        1.0
D           41      -14.0
E           57        2.0
F           48       -7.0
G           65       10.0
H           49       -6.0
I           65       10.0
J           58        3.0

In [19]:
summary_df.mean()

score        55.0
deviation     0.0
dtype: float64

In [20]:
np.mean(deviation **2)

86.000

In [21]:
np.var(scores)

86.000

In [22]:
scores_df.var()

score    95.555556
dtype: float64

In [23]:
summary_df['square of deviation']=np.square(deviation)
summary_df

score  deviation  square of deviation
student                                       
A           42      -13.0                169.0
B           69       14.0                196.0
C           56        1.0                  1.0
D           41      -14.0                196.0
E           57        2.0                  4.0
F           48       -7.0                 49.0
G           65       10.0                100.0
H           49       -6.0                 36.0
I           65       10.0                100.0
J           58        3.0                  9.0

In [24]:
summary_df.mean()

score                  55.0
deviation               0.0
square of deviation    86.0
dtype: float64

In [25]:
np.sqrt(np.var(scores, ddof=0))

9.274

In [26]:
np.std(scores,ddof=0)

9.274